name: Push-to-EC2

on: [push]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "13.38.117.224"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/hotel-miranda-laravel
            sudo git pull

      # - name: Deploy to Server
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SCRIPT_BEFORE: "sudo chown -R ubuntu:ubuntu /var/www/hotel-miranda-laravel/"
      #     SCRIPT_AFTER: "sudo chown -R www-data:www-data /var/www/hotel-miranda-laravel/"
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     REMOTE_HOST: "ec2-13-38-117-224.eu-west-3.compute.amazonaws.com"
      #     REMOTE_USER: "ubuntu"
      #     TARGET: "/var/www/hotel-miranda-laravel/"
